server:
  port: 8899
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: eason
      password: '123456'
      database: cert_db
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy